[package]
name = "profiles"
version = "0.1.0"
edition = "2024"
description = "A fun game where you guess what number the computer has chosen."
license = "MIT OR Apache-2.0"

[dependencies]

[profile.dev]
opt-level = 0 # default, not needed to specify: cargo build

[profile.release]
opt-level = 3 # default, not needed to specify: cargo build --release